version: 2.1

jobs:
  build:
    docker:
      - image: docker:20.10.8 # Define the Docker image version to use
    steps:
      - checkout # Check out your repository's code

      - run:
          name: Install Docker
          command: |
            apk add --update --no-cache docker openrc
            rc-update add docker boot
            service docker start

      - run:
          name: Start Docker Service
          command: |
            service docker start

      # Build the Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t seif1000/docker-frontend -f Dockerfile.dev .

      # Run a specific command within the Docker container
      - run:
          name: Run Command in Docker container
          command: |
            docker run -e CI=true seif1000/docker-frontend npm run test -- --coverage
